import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faUsersCog,
  faFileSignature,
  faThermometerHalf,
  faCloudSunRain,
  faVolumeUp,
  faClock,
  faWifi,
  faCloud,
  faFan,
  faUnlockAlt,
  faPlug,
  faChalkboardTeacher,
  faCogs,
  faFilePdf,
  faFolderOpen,
  faTools,
  faUser,
  faWaveSquare,
  faReply,
  faHandPointUp,
  faLock,
  faExclamation,
  faTimes,
  faCheck
} from "@fortawesome/free-solid-svg-icons";

library.add(
  fab,
  faUsersCog,
  faFileSignature,
  faThermometerHalf,
  faCloudSunRain,
  faVolumeUp,
  faClock,
  faWifi,
  faCloud,
  faFan,
  faUnlockAlt,
  faPlug,
  faChalkboardTeacher,
  faCogs,
  faFilePdf,
  faFolderOpen,
  faTools,
  faUser,
  faWaveSquare,
  faReply,
  faHandPointUp,
  faLock,
  faExclamation,
  faTimes,
  faCheck
);
